name: Cleanup

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  # Clean up old workflow runs
  cleanup-runs:
    name: Cleanup Old Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs older than 30 days
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 10

  # Clean up old artifacts
  cleanup-artifacts:
    name: Cleanup Old Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '30 days'
          skip-recent: 5

  # Clean up old caches
  cleanup-caches:
    name: Cleanup Old Caches
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old caches
        run: |
          echo "Listing old caches..."
          gh cache list --limit 100 | while read cache; do
            CACHE_KEY=$(echo "$cache" | awk '{print $1}')
            CACHE_DATE=$(echo "$cache" | awk '{print $5" "$6}')

            # Calculate age of cache
            CACHE_AGE=$(($(date +%s) - $(date -d "$CACHE_DATE" +%s)))
            THIRTY_DAYS=$((30 * 24 * 60 * 60))

            # Delete caches older than 30 days
            if [ $CACHE_AGE -gt $THIRTY_DAYS ]; then
              echo "Deleting cache: $CACHE_KEY (age: $CACHE_AGE seconds)"
              gh cache delete "$CACHE_KEY" || true
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Report cleanup summary
  cleanup-summary:
    name: Cleanup Summary
    needs: [cleanup-runs, cleanup-artifacts, cleanup-caches]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Generate summary
        run: |
          echo "## Cleanup Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Results" >> $GITHUB_STEP_SUMMARY
          echo "- Workflow runs: ${{ needs.cleanup-runs.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Artifacts: ${{ needs.cleanup-artifacts.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Caches: ${{ needs.cleanup-caches.result }}" >> $GITHUB_STEP_SUMMARY
