name: Frontend CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'apps/forge-ui/**'
      - 'packages/shared-types/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/frontend-deploy.yml'
      - 'deploy/env/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'apps/forge-ui/**'
      - 'packages/shared-types/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Export production frontend env
        id: export-env
        run: |
          node -e "const fs=require('fs');const data=JSON.parse(fs.readFileSync('deploy/env/production.secrets.json','utf-8'));const vars=(data.vercel?.variables||[]).filter(v=>v.targets?.includes('production'));for (const {key,value} of vars){if(!key) continue;fs.appendFileSync(process.env.GITHUB_ENV, `${key}=${value}\n`);}"

      - name: Lint Forge UI
        run: npm run lint --workspace @sepulki/forge-ui

      - name: Run unit tests
        run: npm run test --workspace @sepulki/forge-ui --if-present

      - name: Build Forge UI
        run: npm run build --workspace @sepulki/forge-ui
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: app/

      - name: Deploy to Vercel (Production)
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./app
          github-comment: true

      - name: Comment deployment URL on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Deployed to production: ${{ steps.deploy.outputs.url }}'
            })

  # Job 6: Deploy preview for PRs
  deploy-preview:
    name: Deploy Preview
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: app/

      - name: Deploy to Vercel (Preview)
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./app
          github-comment: true

      - name: Comment preview URL on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔍 Preview deployment ready: ${{ steps.deploy.outputs.url }}'
            })

  # Job 7: Notify on failure (optional)
  notify-failure:
    name: Notify on Failure
    needs: [typecheck, lint, build, deploy]
    runs-on: ubuntu-latest
    if: failure() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Send failure notification
        run: |
          echo "⚠️ Frontend deployment failed for ${{ github.ref }}"
          echo "Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        # Uncomment and configure for Slack/Discord notifications:
        # - name: Slack Notification
        #   uses: rtCamp/action-slack-notify@v2
        #   env:
        #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        #     SLACK_TITLE: Frontend Deployment Failed
        #     SLACK_MESSAGE: 'Deployment failed on ${{ github.ref }}'
        #     SLACK_COLOR: danger
